FROM docker.elastic.co/elasticsearch/elasticsearch:6.3.0

ENV ES_JAVA_OPTS="-Des.path.conf=/etc/elasticsearch"

#RUN /usr/share/elasticsearch/bin/elasticsearch-plugin install x-pack

#CMD ["-e", "network.host=0.0.0.0", "-e", "discovery.zen.minimum_master_nodes=1"]
